from datetime import datetime, timedelta
from typing import Optional, Dict, Any, List
from bson import ObjectId
from fastapi import HTTPException, status
from ..config.database import Database, Collections
from ..utils.logger import logger
from ..models.user import User, UserInDB, UserCreate, AccountActivity # Added User
from ..models.payment import PaymentInDB
from ..models.order import OrderInDB, AutoOrderInDB
from ..utils.security import get_password_hash # Import password hashing utility

class UserService:
    @staticmethod
    async def create_user(user_data: UserCreate) -> User: # Return User, not UserInDB
        db = Database.get_db()
        
        existing_user = await db[Collections.USERS].find_one({"email": user_data.email})
        if existing_user:
            # Use HTTPException for routes to catch and return proper responses
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="User with this email already exists"
            )

        existing_username = await db[Collections.USERS].find_one({"username": user_data.username})
        if existing_username:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="User with this username already exists"
            )

        hashed_password = get_password_hash(user_data.password)
        
        # Create user document for DB insertion
        # UserInDB model should ideally handle the _id to id mapping if PyObjectId is used for id field
        user_db_data = UserInDB(
            username=user_data.username,
            email=user_data.email,
            profile_image=user_data.profile_image, # from UserBase
            stats=user_data.stats, # from UserBase, defaults to UserStats()
            hashed_password=hashed_password,
            credits=0.0,  # New users start with 0 credits
            joined_date=datetime.utcnow(),
            # id will be generated by MongoDB or should be handled by model if PyObjectId is used for id
        )
        
        # Pydantic's `model_dump` (v2) or `dict` (v1) with `by_alias=True` is good for DB
        user_dict_for_db = user_db_data.model_dump(by_alias=True)

        # Remove 'id' if it's None and handled by DB, or ensure PyObjectId creates it if it's part of the model before insert
        # If 'id' is an ObjectId field in UserInDB, it's fine. If it's aliased from '_id', don't include it in insert.
        # Current UserInDB has `id: str`. This is tricky. Assuming _id is the PK.
        # Let's remove 'id' from the dict if it's there to let MongoDB generate _id.
        # However, UserInDB expects 'id'. This model structure might need revision for proper _id handling.
        # For now, let's assume UserInDB's id field is meant to be populated *after* insertion from _id.

        # A common pattern:
        # user_to_insert = user_db_data.model_dump(exclude_none=True, exclude={'id'}) # if id is optional before creation
        # result = await db[Collections.USERS].insert_one(user_to_insert)
        # created_user_id = result.inserted_id
        # db_user = await db[Collections.USERS].find_one({"_id": created_user_id})
        # return User(**db_user) if db_user else None
        
        # Simplified approach given current UserInDB requiring 'id: str'
        # This implies 'id' should be set before validation or is an alias for '_id' (which it isn't currently)
        # Let's assume for now that we let MongoDB generate _id and then populate User from that.

        result = await db[Collections.USERS].insert_one(user_dict_for_db)
        created_user_id = result.inserted_id

        # Fetch the user from DB to ensure all fields are correctly populated, including the DB-generated _id
        db_user_data = await db[Collections.USERS].find_one({"_id": created_user_id})

        if db_user_data:
            # Convert _id to string for the 'id' field if needed by Pydantic model
            # The User model expects 'id', not '_id'.
            # User model also doesn't have profile_image and stats by default, it inherits from UserBase
            # which UserInDB also inherits. User model should be fine.

            # Ensure the data fetched from DB (with _id) is correctly mapped to the User model (with id)
            # The User model has `Config.from_attributes = True` which helps.
            # If UserInDB has PyObjectId for id, it handles the _id mapping.
            # If id is just a string, manual mapping of _id to id might be needed before User(**db_user_data)
            # For now, assuming User model can handle db_user_data (e.g. by having an alias or if _id is manually mapped)

            # Let's ensure the id is correctly populated from _id for the User model
            final_user_data_for_model = {**db_user_data, "id": str(db_user_data["_id"])}

            logger.info("user_created", user_id=str(created_user_id), email=user_data.email)
            return User(**final_user_data_for_model) # Return User model instance
        else:
            # This case should ideally not happen if insert was successful
            raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail="Failed to create user after insertion.")


    @staticmethod
    async def get_user(user_id: str) -> Optional[UserInDB]:
        db = Database.get_db()
        user_data = await db[Collections.USERS].find_one({"_id": ObjectId(user_id)})
        if user_data:
            return UserInDB(**user_data)
        return None

    @staticmethod
    async def get_user_by_email(email: str) -> Optional[UserInDB]:
        db = Database.get_db()
        user_data = await db[Collections.USERS].find_one({"email": email})
        if user_data:
            return UserInDB(**user_data)
        return None

    @staticmethod
    async def update_credits(user_id: str, amount: float) -> bool:
        db = Database.get_db()
        result = await db[Collections.USERS].update_one(
            {"_id": ObjectId(user_id)},
            {"$inc": {"credits": amount}}
        )
        return result.modified_count > 0

    @staticmethod
    async def get_account_activity(
        user_id: str,
        start_date: datetime,
        end_date: Optional[datetime] = None
    ) -> List[AccountActivity]:
        """Get user's account activity for a date range"""
        try:
            db = Database.get_db()
            if end_date is None:
                end_date = datetime.utcnow()

            # Get all orders in the date range
            orders = await db[Collections.ORDERS].find({
                "user_id": user_id,
                "created_at": {"$gte": start_date, "$lte": end_date}
            }).to_list(None)

            # Get all payments in the date range
            payments = await db[Collections.PAYMENTS].find({
                "user_id": user_id,
                "created_at": {"$gte": start_date, "$lte": end_date}
            }).to_list(None)

            # Group by date
            activity_by_date = {}
            current_date = start_date
            while current_date <= end_date:
                date_key = current_date.strftime("%Y-%m-%d")
                activity_by_date[date_key] = {
                    "orders": 0,
                    "credits": 0.0
                }
                current_date += timedelta(days=1)

            # Count orders per day
            for order in orders:
                date_key = order["created_at"].strftime("%Y-%m-%d")
                activity_by_date[date_key]["orders"] += 1

            # Sum credits per day
            for payment in payments:
                if payment["status"] == "completed":
                    date_key = payment["created_at"].strftime("%Y-%m-%d")
                    activity_by_date[date_key]["credits"] += payment["amount"]

            # Convert to AccountActivity objects
            activities = []
            for date_key, data in activity_by_date.items():
                activity = AccountActivity(
                    id=str(ObjectId()),
                    user_id=user_id,
                    date=datetime.strptime(date_key, "%Y-%m-%d"),
                    orders=data["orders"],
                    credits=data["credits"]
                )
                activities.append(activity)

            return activities

        except Exception as e:
            logger.error("get_account_activity_failed", error=str(e))
            raise

    @staticmethod
    async def update_user_stats(user_id: str):
        """Update user's order statistics"""
        try:
            db = Database.get_db()
            
            # Get order counts
            total_orders = await db[Collections.ORDERS].count_documents({
                "user_id": user_id
            })
            
            active_orders = await db[Collections.ORDERS].count_documents({
                "user_id": user_id,
                "status": {"$in": ["pending", "in-progress"]}
            })
            
            completed_orders = await db[Collections.ORDERS].count_documents({
                "user_id": user_id,
                "status": "completed"
            })

            # Update user stats
            await db[Collections.USERS].update_one(
                {"_id": ObjectId(user_id)},
                {
                    "$set": {
                        "stats": {
                            "total_orders": total_orders,
                            "active_orders": active_orders,
                            "completed_orders": completed_orders
                        }
                    }
                }
            )

            logger.info("user_stats_updated",
                user_id=user_id,
                total_orders=total_orders,
                active_orders=active_orders,
                completed_orders=completed_orders
            )

        except Exception as e:
            logger.error("update_user_stats_failed", error=str(e))
            raise

    @staticmethod
    async def create_payment(user_id: str, payment_data: Dict[str, Any]) -> PaymentInDB:
        db = Database.get_db()
        
        # Create payment document
        payment = PaymentInDB(
            user_id=ObjectId(user_id),
            amount=payment_data["amount"],
            method=payment_data["method"],
            description=payment_data["description"],
            payment_details=payment_data["payment_details"]
        )
        
        # Insert into database
        result = await db[Collections.PAYMENTS].insert_one(payment.dict(by_alias=True))
        payment.id = result.inserted_id
        
        # Update user credits
        await UserService.update_credits(user_id, payment_data["amount"])
        
        logger.info("payment_created",
            payment_id=str(payment.id),
            user_id=user_id,
            amount=payment_data["amount"]
        )
        
        return payment 